---
apiVersion: v1
kind: ReplicationController
metadata:
 name: node-rc
spec:
 replicas: 2
 selector:
  name: node-pod
 template:
  metadata:
   labels:
    name: node-pod
  spec:
   containers:
   - name: node-pod
     image: xiaoqi8866/test-nodejs
     ports:
     - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: node-service
spec:
 ports:
 - port: 8080
 selector:
  name: node-pod
